language: node_js
node_js:
  - "5.5"
  - "4.2"
language: python
python:
  - "3.5"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
env:
  global:
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
script:
  # - pytest # or py.test for Python versions 3.5 and below
  - py.test --cov=application tests/
after_success:
  - codecov
  - coverage xml
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
