services:
  - docker
matrix:
  include:
    - node_js: "node"
      language: node_js
      script:
        - cd backend
        - yarn
        - yarn global add typescript
        - tsc
        - rm -rf ./**/*.ts
        - rm -rf ./**/*.js.map
        - cd ../shared
        - yarn
        - tsc
        - rm -rf ./**/*.ts
        - rm -rf ./**/*.js.map
        - cd ..
        - ls
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build . -f ./backend/Dockerfile -t shuhelper-backend
        - docker tag shuhelper-backend $DOCKER_USERNAME/shuhelper-backend
        - docker push $DOCKER_USERNAME/shuhelper-backend
    - node_js: "node"
      language: node_js
      script:
        - cd frontend
        - yarn global add nuxt
        - yarn
        - yarn build
        - cd ..
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build . -f ./frontend/Dockerfile -t shuhelper-frontend
        - docker tag shuhelper-frontend $DOCKER_USERNAME/shuhelper-frontend
        - docker push $DOCKER_USERNAME/shuhelper-frontend
