services:
  - docker

addons:
  ssh_known_hosts: helper.gtmdcm.com

matrix:
  include:
    - node_js: node
      language: node_js
      before_install:
        - openssl aes-256-cbc -K $encrypted_656ce386c8d6_key -iv $encrypted_656ce386c8d6_iv
          -in deploy_key.enc -out ./deploy_key -d
        - eval "$(ssh-agent -s)"
        - chmod 600 ./deploy_key
        - ssh-add ./deploy_key
      script:
        - cd backend
        - yarn
        - yarn global add typescript
        - tsc
        - rm -rf ./**/*.ts
        - rm -rf ./**/*.js.map
        - cd ../shared
        - yarn
        - tsc
        - rm -rf ./**/*.ts
        - rm -rf ./**/*.js.map
        - cd ..
        - ls
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build . -f ./backend/Dockerfile -t shuhelper-backend
        - docker tag shuhelper-backend $DOCKER_USERNAME/shuhelper-backend
        - docker push $DOCKER_USERNAME/shuhelper-backend
        - sleep 10
        - ssh -i ./deploy_key root@helper.gtmdcm.com ./deploy.sh
        - ssh -i ./deploy_key root@helper.gtmdcm.com touch backend_success.txt
    - node_js: node
      language: node_js
      before_install:
        - openssl aes-256-cbc -K $encrypted_656ce386c8d6_key -iv $encrypted_656ce386c8d6_iv
          -in deploy_key.enc -out ./deploy_key -d
        - ls
        - eval "$(ssh-agent -s)"
        - chmod 600 ./deploy_key
        - ssh-add ./deploy_key
        - ssh -i ./deploy_key root@helper.gtmdcm.com touch success2.tmp
      script:
        - cd frontend
        - yarn global add nuxt
        - yarn
        - yarn build
        - cd ..
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build . -f ./frontend/Dockerfile -t shuhelper-frontend
        - docker tag shuhelper-frontend $DOCKER_USERNAME/shuhelper-frontend
        - docker push $DOCKER_USERNAME/shuhelper-frontend
        - sleep 10
        - ssh -i ./deploy_key root@helper.gtmdcm.com ./deploy.sh
        - ssh -i ./deploy_key root@helper.gtmdcm.com touch frontend_success.txt
