version: '3'
services:
  mongodb:
    image: 'mongo'
    restart: always

  redis:
    image: 'redis:5.0.3-alpine'
    restart: always

  backend:
    image: 'longfangsong/shuhelper-backend'
    environment:
      JWT_SECRET: CHANGE_WHEN_DEPLOY
      MONGODB_ADDRESS: 'mongodb://mongodb'
      REDIS_ADDRESS: 'redis'
    ports:
      - "3001:3001"
    restart: always
  # 此处 depends_on 仅供参考用
  # 由于docker-compose只能保证容器的启动顺序，而不保证容器中的服务已经启动
  # 故实际启动顺序的编排由 shell 脚本执行
  # depends_on:
  #   - mongodb
  #   - redis

  frontend:
    image: 'longfangsong/shuhelper-frontend'
    environment:
      BASE_URL: "http://backend:3001"
      AUTH_BACKEND_URL: "http://backend:3001"
      API_BACKEND_URL: "http://backend:3001"
    ports:
      - "80:80"
    restart: always
  # 此处 depends_on 仅供参考用
  # 由于docker-compose只能保证容器的启动顺序，而不保证容器中的服务已经启动
  # 故实际启动顺序的编排由 shell 脚本执行
  #    depends_on:
  #      - backend